version: "3.8"
services:
  ipproject:
    image: sem16 # TODO Use Team as illustrated in document for example [sem01 or crd01]. Don't remove the comment. 
    build: .
    volumes:
      - ${INPUT_TEST}:${INPUT_TEST}:ro
      - ${OUTPUT_TEST}:${OUTPUT_TEST}
    environment:
      INPUT_TEST: ${INPUT_TEST}
      OUTPUT_TEST: ${OUTPUT_TEST}
